name: Deploy to DigitalOcean Droplet
on:
  push:
    branches: [ main ] 

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PW: ${{ secrets.DOCKERHUB_PW }}
  GITHUB_SHA: ${{ github.sha }}
  PORT: ${{ secrets.PORT }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PW: ${{ secrets.DB_PW }}
  DB_PORT: ${{ secrets.DB_PORT }}
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY: ${{ secrets.KEY }}

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PW }}

      - name: Build and tag image
        run: |
          IMAGE_NAME=${{ env.DOCKERHUB_USERNAME }}/be-log-let:${{ env.GITHUB_SHA }}
          docker build -t $IMAGE_NAME .

      - name: check docker image 
        run: |
          docker images

      - name: Tag and Push App Image
        run: |
          IMAGE_NAME=${{ env.DOCKERHUB_USERNAME }}/be-log-let:${{ env.GITHUB_SHA }}
          docker push $IMAGE_NAME

      
        
  deploy:
    name: Deploy to Droplet
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: |
            IMAGE=${{ env.DOCKERHUB_USERNAME }}/be-log-let:${{ env.GITHUB_SHA }}
            echo "${{ env.DOCKERHUB_PW }}" \
              | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin
            # pull latest
            docker compose pull
            # stop & remove old
            docker stop myapp 2>/dev/null || true
            docker rm   myapp 2>/dev/null || true
            docker stop mydb 2>/dev/null || true
            docker rm   mydb   2>/dev/null || true
            # run new
            docker compose up -d
