name: Deploy to DigitalOcean Droplet
on:
  push:
    branches: [ main ] 

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  GITHUB_SHA: ${{ github.sha }}
  PORT: ${{ secrets.PORT }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PW: ${{ secrets.DB_PW }}
  DB_PORT: ${{ secrets.DB_PORT }}

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Check env
        run: |
          echo "DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}"
          echo "GITHUB_SHA: ${{ env.GITHUB_SHA }}"
          echo "PORT: ${{ env.PORT }}"
          echo "DB_HOST: ${{ env.DB_HOST }}"
          echo "DB_USER: ${{ env.DB_USER }}"

      - name: Build and tag image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/be-log-let:${{ github.sha }}
          docker build -t $IMAGE_NAME .

      - name: Tag and Push App Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/be-log-let:${{ github.sha }}
          docker tag be-log-let_app $IMAGE_NAME
          docker push $IMAGE_NAME

      - name: Set output tag
        id: meta
        run: |
          echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
        
  deploy:
    name: Deploy to Droplet
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: check env
        run: |
          echo "DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}"
          echo "GITHUB_SHA: ${{ env.GITHUB_SHA }}"
          echo "PORT: ${{ env.PORT }}"
          echo "DB_HOST: ${{ env.DB_HOST }}"
          echo "DB_USER: ${{ env.DB_USER }}"
          echo "DB_PW: ${{ env.DB_PW }}"
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/be-log-let:${{ needs.build-and-push.outputs.tag }}
            echo "${{ secrets.DOCKERHUB_PW }}" \
              | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            # pull latest
            docker-compose pull
            # stop & remove old
            docker stop myapp  || true
            docker rm   myapp  || true
            docker stop mydb  || true
            docker rm   mydb  || true
            # run new
            docker-compose up -d
